plugins {
    id 'com.android.application' version '8.2.2' apply false
    id 'com.android.library' version '8.2.2' apply false
}

allprojects {
    group = findProperty("GROUP") ?: "com.github.zhenglongzhang"
    version = findProperty("VERSION_NAME") ?: "1.0.0"
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}
